version: '3'

tasks:
  build:
    desc: Build the project
    cmds:
      - dotnet build -c Release

  install:
    desc: Build and install as global tool
    deps: [build]
    cmds:
      - dotnet pack -c Release -o ./nupkg
      - dotnet tool uninstall -g CodeXPath || true
      - dotnet tool install -g CodeXPath --add-source ./nupkg
