version: '3'

tasks:
  build:
    desc: Build the project
    cmds:
      - dotnet build CodeXTractor.csproj -c Release

  install:
    desc: Build and install as global tool
    deps: [build]
    cmds:
      - dotnet pack CodeXTractor.csproj -c Release -o ./nupkg
      - dotnet tool uninstall -g CodeXTractor || true
      - dotnet tool install -g CodeXTractor --add-source ./nupkg

  run:
    desc: Run the CLI with arguments
    cmds:
      - dotnet run --project CodeXTractor.csproj -- {{.CLI_ARGS}}
