version: '3'

vars:
  DIST_DIR: ./dist

tasks:
  # === tractor (Rust XPath CLI) ===

  build:
    desc: Build tractor (release)
    cmds:
      - cargo build --release -p tractor

  install:
    desc: Build and install tractor to ~/.cargo/bin
    cmds:
      - cargo install --path tractor

  run:
    desc: Run tractor with arguments
    cmds:
      - cargo run --release -p tractor -- {{.CLI_ARGS}}

  test:
    desc: Run tests
    cmds:
      - cargo test

  test:integration:
    desc: Run integration tests
    deps: [build]
    cmds:
      - bash tests/integration/test.sh

  test:snapshots:
    desc: Regenerate XML snapshots and verify they match committed versions
    deps: [build]
    cmds:
      - bash tests/integration/test_snapshots.sh

  # === Distribution builds ===

  dist:linux:
    desc: Build for Linux (via Docker)
    cmds:
      - mkdir -p {{.DIST_DIR}}/linux-x64
      - docker build -t tractor-builder -f Dockerfile.build .
      - docker run --rm -v "{{.PWD}}:/src" tractor-builder
          cargo build --release --target x86_64-unknown-linux-gnu
      - cp target/x86_64-unknown-linux-gnu/release/tractor {{.DIST_DIR}}/linux-x64/
    vars:
      PWD:
        sh: pwd

  dist:windows:
    desc: Build for Windows (native)
    cmds:
      - mkdir -p {{.DIST_DIR}}/windows-x64
      - cargo build --release
      - cp target/release/tractor.exe {{.DIST_DIR}}/windows-x64/

  # === Maintenance ===

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist/
      - rm -rf target/
