// Auto-generated by: task grammar:from-source LANG=csharp REPO=tree-sitter/tree-sitter-c-sharp REF=master
// @ts-ignore
import wasm from '/grammars/tree-sitter-c_sharp.wasm?url';
export default wasm;
