// Auto-generated by: task grammar:generate-index
// Re-exports all grammar WASM URLs

export { default as bash } from './bash';
export { default as c } from './c';
export { default as cpp } from './cpp';
export { default as csharp } from './csharp';
export { default as css } from './css';
export { default as go } from './go';
export { default as html } from './html';
export { default as java } from './java';
export { default as javascript } from './javascript';
export { default as json } from './json';
export { default as php } from './php';
export { default as python } from './python';
export { default as ruby } from './ruby';
export { default as rust } from './rust';
export { default as tsx } from './tsx';
export { default as typescript } from './typescript';
