// Auto-generated by: task grammar:from-npm LANG=javascript PACKAGE=tree-sitter-javascript
// @ts-ignore
import wasm from 'tree-sitter-javascript/tree-sitter-javascript.wasm?url';
export default wasm;
