// Auto-generated by: task grammar:from-npm LANG=typescript PACKAGE=tree-sitter-typescript
// @ts-ignore
import wasm from 'tree-sitter-typescript/tree-sitter-typescript.wasm?url';
export default wasm;
