// Auto-generated by: task grammar:from-npm LANG=yaml PACKAGE=@tree-sitter-grammars/tree-sitter-yaml
// @ts-ignore
import wasm from '@tree-sitter-grammars/tree-sitter-yaml/tree-sitter-yaml.wasm?url';
export default wasm;
