//! Hand-curated `EnvKind` enum.
//!
//! .env files are parsed with `tree-sitter-bash`, but only a tiny
//! subset of bash's 59 grammar kinds appears in well-formed .env
//! content. Listing them all in a generated enum would produce 50+
//! arms of passthrough noise in `rules.rs`. This curated enum
//! covers exactly the kinds the env transform reads — anything else
//! the parser produces falls through the orchestrator's
//! `from_str`-returns-`None` branch as a no-op.
//!
//! NOT generated by `task gen:kinds`. Add a variant here when the
//! transform needs to handle a new bash construct.

use strum_macros::{EnumString, IntoStaticStr};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, EnumString, IntoStaticStr)]
#[strum(serialize_all = "snake_case")]
pub enum EnvKind {
    /// `KEY=value` assignment.
    VariableAssignment,
    /// `export KEY=value` — wraps a `variable_assignment`.
    DeclarationCommand,
    /// `# foo` — a single-line comment.
    Comment,
    /// Top-level node from `tree-sitter-bash`. Renamed to `<document>`.
    Program,
    /// The identifier in `KEY=value`.
    VariableName,
    /// Bare word value: `KEY=value`.
    Word,
    /// Numeric value: `KEY=123`.
    Number,
    /// Single-quoted: `KEY='val'`.
    RawString,
    /// ANSI-C escapes: `KEY=$'val'`.
    AnsiiCString,
    /// Double-quoted string wrapper.
    String,
    /// Inside a double-quoted string.
    StringContent,
    /// `KEY=$VAR`.
    SimpleExpansion,
    /// `KEY=${VAR}`.
    Expansion,
    /// Adjacent value parts that concatenate at parse time.
    Concatenation,
}

impl EnvKind {
    pub fn from_str(s: &str) -> Option<Self> {
        <Self as std::str::FromStr>::from_str(s).ok()
    }

    pub fn as_str(&self) -> &'static str {
        (*self).into()
    }
}
