//! Code-language (SyntaxTree) variant-blind projections.
//!
//! Sits alongside `tree/data/` (data languages) and `tree/sql/`
//! (T-SQL). The SyntaxTree enum itself still lives at
//! `tree/types.rs` for now; this module groups everything that
//! consumes it as a source of truth for rendering.
//!
//! ## Layout
//!
//! - [`metadata_generated`] — reflection metadata over `SyntaxTree`
//!   (`element_name_of`, `flags_of`). Auto-generated by
//!   `bin/gen_metadata.rs`; reviewable plain Rust.
//! - [`to_xot`] — variant-blind walker producing an `xot::Xot` tree
//!   (XML). Uses only the metadata accessors + `SyntaxTree::children`.
//! - [`to_json`] — variant-blind walker producing a
//!   `serde_json::Value` directly from the tree. Same metadata; no
//!   XML intermediate. YAML re-encodes this Value via `serde_yaml`.
//!
//! The walkers hold zero per-variant knowledge. All shape decisions
//! live in the metadata, which is itself derived mechanically from
//! the `SyntaxTree` field types.

pub mod types;
pub mod to_xot;
pub mod to_json;
pub mod element_naming;

// The on-disk filename keeps a `.generated.` infix to signal that it
// is auto-emitted; the Rust module name uses an underscore because
// `.` is illegal in identifiers.
#[path = "metadata.generated.rs"]
pub mod metadata_generated;
