/**
 * Tractor WASM module wrapper
 */

import type { SerializedNode } from './parser';

// Import the WASM module (generated by wasm-pack)
// @ts-ignore - Module will be generated by wasm-pack
import init, { parseToXml, parseAstToXml, getSupportedLanguages, hasTransforms } from '../pkg/tractor_core.js';

let initialized = false;

/**
 * Initialize the Tractor WASM module
 */
export async function initTractor(): Promise<void> {
  if (initialized) return;
  await init();
  initialized = true;
}

/** Parse request format */
export interface ParseRequest {
  ast: SerializedNode;
  source: string;
  language: string;
  filePath?: string;
  rawMode?: boolean;
  includeLocations?: boolean;
  prettyPrint?: boolean;
}

/** Parse response format */
export interface ParseResponse {
  xml: string;
  warnings: string[];
}

/**
 * Parse AST to XML using the full request format
 */
export async function parseToXmlFull(request: ParseRequest): Promise<ParseResponse> {
  await initTractor();
  const responseJson = parseToXml(JSON.stringify(request));
  return JSON.parse(responseJson);
}

/**
 * Parse AST to XML using simple parameters
 */
export async function parseAstToXmlSimple(
  ast: SerializedNode,
  source: string,
  language: string,
  rawMode: boolean = false,
  includeLocations: boolean = true,
  prettyPrint: boolean = true
): Promise<string> {
  await initTractor();
  return parseAstToXml(JSON.stringify(ast), source, language, rawMode, includeLocations, prettyPrint);
}

/**
 * Get list of supported languages from the WASM module
 */
export async function getTractorLanguages(): Promise<string[]> {
  await initTractor();
  return JSON.parse(getSupportedLanguages());
}

/**
 * Check if a language has semantic transforms
 */
export async function languageHasTransforms(language: string): Promise<boolean> {
  await initTractor();
  return hasTransforms(language);
}
